version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - nest-postgres
    env_file:
      - .env

  nest-postgres:
    image: postgres:13
    container_name: nest-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

  test-db:
    image: postgres:13
    container_name: test-db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - test-db:/var/lib/postgresql/data

volumes:
  nest-postgres:
    name: nest-postgres-db
  test-db:
    name: test-postgres-db
